### ISSUE TITLE
Extension fails on WebSocket authentication in JupyterHub

### ISSUE THREAD

**Issue by matthewwiese** [Wh1isper/jupyter_kernel_executor#9]
A really compelling use for this extension is in a multi-user environment like [JupyterHub](https://jupyter.org/hub) where users can submit notebook cells for background execution. Additionally, this extension can improve UX in cases of poor network access as computation is not interrupted. Unfortunately, as it currently exists this extension does not work in JupyterHub.

A `WSServerHandshakeError` is raised on a POST request to the execute endpoint. I have tracked down the problem, which is that in JupyterHub token authentication is broken - `self.token` is not populated with the token string. Whereas this extension works as expected in JupyterLab. The full error:

```
[E 2022-12-19 11:34:55.342 SingleUserLabApp web:1798] Uncaught exception POST /user/matt/api/kernels/0c2afc52-b7fb-4a06-b8f2-f1c85167dd41/execute (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/user/matt/api/kernels/0c2afc52-b7fb-4a06-b8f2-f1c85167dd41/execute', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1')
    Traceback (most recent call last):
      File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/jupyter_kernel_executor/handlers.py", line 138, in post
        await self.execute(client, code, document_id, cell_id)
      File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/jupyter_kernel_executor/handlers.py", line 153, in execute
        result = await client.execute(code)
      File "/Users/matt/github/jupyter_kernel_client/jupyter_kernel_client/client.py", line 109, in execute
        async with session.ws_connect(
      File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
        self._resp = await self._coro
      File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/aiohttp/client.py", line 795, in _ws_connect
        raise WSServerHandshakeError(
    aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('ws://127.0.0.1:57936/user/matt/api/kernels/0c2afc52-b7fb-4a06-b8f2-f1c85167dd41/channels?session_id=00164db0-f768-498b-a60c-725058e7bf05')
```

My hacky fix is to extract the token from the `Authorization` header using Tornado. On [line 109](https://github.com/Wh1isper/jupyter_kernel_executor/blob/master/jupyter_kernel_executor/handlers.py#L109) of `handlers.py` where we instantiate the `KernelWebsocketClient`, change it to:

```python
auth_header = self.request.headers.get('Authorization')
request_token = auth_header.split(' ')[1]

client = KernelWebsocketClient(
    kernel_id = kernel_id,
    host = self.serverapp.ip,
    port = self.serverapp.port,
    base_url = self.base_url,
    token = request_token,
    encoded = True,
)
```

Which fixes this bug in JupyterHub without affecting JupyterLab.

I'm still familiarizing myself with Jupyter's backend, and so am not sure what the best practice is. Do you have any suggestions on how to resolve this the Jupyter way?

**Comment by Wh1isper** [comment]
@matthewwiese Thank you for your feedback

Jupyterhub uses a `minxin class` to create a compatible Application class with JupyterHub authentication mixins enabled, 
called `SingleuserApp`: https://github.com/jupyterhub/jupyterhub/tree/main/jupyterhub/singleuser

I think we can use some authentication options in the request, such as `cookies`, `Authorization header`, and use `self.token` as a fallback option

This is already provided in the client as `auth_header`: https://github.com/Wh1isper/jupyter_kernel_client/blob/master/jupyter_kernel_client/client.py#L61

What we need to do is something like

```python
auth_header = self.get_request_auth(self.request) # -> Dict() or dict with auth info
if not auth_header:
  auth_header = self.get_auth_header() # {Authorization:f"token {self.token}"}
client = KernelWebsocketClient(
    kernel_id = kernel_id,
    host = self.serverapp.ip,
    port = self.serverapp.port,
    base_url = self.base_url,
    auth_header = auth_header,
    encoded = True,
)
```

Could you open a pr for it? Or I may implement it about this week

**Comment by Wh1isper** [comment]
I open a pr for it https://github.com/Wh1isper/jupyter_kernel_executor/pull/10

Can you help me try to see if this branch works? I don't have a JupyterHub related environment @matthewwiese 

https://github.com/Wh1isper/jupyter_kernel_executor/pull/10

**Comment by Wh1isper** [comment]
fixed in https://github.com/Wh1isper/jupyter_kernel_executor/pull/10
